### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by ThisIsMonta** [pmndrs/xr#359]
Looks like something broken while accessing VR.

```
index-qKWNutEx.js:3914 TypeError: coordinateSystem._transformBasePoseMatrix is not a function
    at GamepadXRInputSource.getXRPose (webxr-polyfill.js:5656:24)
    at EmulatedXRDevice.getInputPose (webxr-polyfill.js:28585:36)
    at XRFrame.getPose (webxr-polyfill.js:3520:23)
    at index-qKWNutEx.js:4125:1365
    at Object.current (index-qKWNutEx.js:4125:59654)
    at O0 (index-qKWNutEx.js:3914:21281)
    at g (index-qKWNutEx.js:3914:22164)
    at P (index-qKWNutEx.js:3914:25279)
    at Ge (index-qKWNutEx.js:3880:8450)
    at Object.s [as callback] (index-qKWNutEx.js:83:4307)
```

Even the hosted examples has the same issue. [Pmndrs ragdoll grab example](https://pmndrs.github.io/xr/examples/rag-doll)

Managed to skip the error after setting `controller: false` while creating the XRStore. but until when ?

**Comment by bbohlender** [comment]
As you can see in your error, the issue comes from the webxr-polyfill you are using. I assume your using IWER 1.0 (which uses this outdated Polyfill). As written in the documentation. This emulator is outdated and not supported. See this for a replacement:
https://pmndrs.github.io/xr/docs/getting-started/development-setup
